apiVersion: v1
kind: ConfigMap
metadata:
  name: global-data-config
  labels:
    app: postgres-redis
data:
  REDIS_HOST: {{ .Values.redis.host }}
  REDIS_PORT: {{ quote .Values.redis.port }}
  PGHOST: {{ .Values.postgres.host }}
  PGUSER: {{ .Values.postgres.user }}
  PGDATABASE: {{ .Values.postgres.database }}
  PGPORT: {{ quote .Values.postgres.port }}
