apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.metadata.server }}
spec:
  replicas: {{ .Values.replica.server }}
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: {{ .Values.deployment.user }}/hungerstation-server
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: {{ .Values.resources.server.requests.cpu }}
              memory: {{ .Values.resources.server.requests.memory }}
            limits:
              cpu: {{ .Values.resources.server.limits.cpu }}
              memory: {{ .Values.resources.server.limits.memory }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.readinessProbe.server.port }}
            initialDelaySeconds: {{ .Values.readinessProbe.server.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.server.timeoutSeconds }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.readinessProbe.server.port }}
            initialDelaySeconds: {{ .Values.readinessProbe.server.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.server.timeoutSeconds }}
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret-config
                  key: PGPASSWORD
          envFrom:
            - configMapRef:
                name: global-data-config

